
ALTER TABLE PNCS_LEGO_MAP DROP CONSTRAINT FK_PNCS_LEGO_MAP_DISCERNABLE_ENID;
ALTER TABLE PNCS_LEGO_MAP DROP CONSTRAINT FK_PNCS_LEGO_MAP_QUALIFIER_ENID;
ALTER TABLE PNCS_LEGO_MAP DROP CONSTRAINT FK_PNCS_LEGO_MAP_VALUE_ENID;
ALTER TABLE ASSERTIONS DROP CONSTRAINT FK_ASSERTIONS_DNID;
ALTER TABLE ASSERTIONS DROP CONSTRAINT FK_ASSERTIONS_INID;
ALTER TABLE ASSERTIONS DROP CONSTRAINT FK_ASSERTIONS_VALUE_ENID;
ALTER TABLE ASSERTIONS DROP CONSTRAINT FK_ASSERTIONS_QUALIFIER_ENID;
ALTER TABLE ASSERTIONS DROP CONSTRAINT FK_ASSERTIONS_DISCERNABLE_ENID;
ALTER TABLE ASSERTIONS DROP CONSTRAINT FK_ASSERTIONS_SECTION_ENID;
ALTER TABLE DOCUMENTS DROP CONSTRAINT FK_DOCUMENTS_INID;
ALTER TABLE DOCUMENTS DROP CONSTRAINT FK_DOCUMENTS_PROVIDERNID;
ALTER TABLE DOCUMENTS DROP CONSTRAINT FK_DOCUMENTS_PATIENTNID;


DROP TABLE ASSERTIONS;
DROP TABLE DOCUMENTS;
DROP TABLE EXPRESSIONS;
DROP TABLE INTERVALS;
DROP TABLE PERSONS;
DROP TABLE PNCS_LEGO_MAP;

CREATE TABLE ASSERTIONS  ( 
	AUUID           	CHAR(36) NOT NULL,
	DNID            	INTEGER NOT NULL,
	SEQ_IN_DOC      	SMALLINT NOT NULL,
	SECTION_ENID    	INTEGER NOT NULL,
	DISCERNABLE_ENID	INTEGER NOT NULL,
	QUALIFIER_ENID  	INTEGER NOT NULL,
	VALUE_ENID      	INTEGER NOT NULL,
	INID            	INTEGER NOT NULL,
	PRIMARY KEY(AUUID)
);
CREATE TABLE DOCUMENTS  ( 
	DUUID      	CHAR(36) UNIQUE,
	DNID       	INTEGER GENERATED ALWAYS AS IDENTITY,
	PATIENTNID 	INTEGER NOT NULL,
	PROVIDERNID	INTEGER,
	INID       	INTEGER NOT NULL,
	PRIMARY KEY(DNID)
);
CREATE TABLE EXPRESSIONS  ( 
	EXPRESSION	VARCHAR(2048) NOT NULL,
	EUUID     	CHAR(36) UNIQUE,
	ENID      	INTEGER GENERATED ALWAYS AS IDENTITY,
	CNID      	INTEGER NOT NULL,
	PRIMARY KEY(ENID)
);
CREATE TABLE INTERVALS  ( 
	ISTART	DATE NOT NULL,
	IEND  	DATE NOT NULL,
	IUUID 	CHAR(36) UNIQUE,
	INID  	INTEGER GENERATED ALWAYS AS IDENTITY,
	PRIMARY KEY(INID)
);
CREATE TABLE PERSONS  ( 
	PUUID    	CHAR(36) UNIQUE,
	PNID     	INTEGER GENERATED ALWAYS AS IDENTITY,
	LASTNAME 	VARCHAR(128) NOT NULL,
	FIRSTNAME	VARCHAR(128) NOT NULL,
	DOB      	DATE NOT NULL,
	PRIMARY KEY(PNID)
);
CREATE TABLE PNCS_LEGO_MAP (
        MAP_ID INTEGER GENERATED ALWAYS AS IDENTITY,
        PNCS_ID INTEGER UNIQUE,
        PNCS_VALUE VARCHAR(256) not null,
        DISCERNABLE_ENID INTEGER not null,
        QUALIFIER_ENID INTEGER not null,
        VALUE_ENID INTEGER not null,
        PRIMARY KEY(MAP_ID)
);
CREATE INDEX ASSERTIONS_DNID_IDX
	ON ASSERTIONS(DNID);
CREATE INDEX ASSERTIONS_SECTION_ENID_IDX
	ON ASSERTIONS(SECTION_ENID);
CREATE INDEX ASSERTIONS_DISCERNABLE_ENID_IDX
	ON ASSERTIONS(DISCERNABLE_ENID);
CREATE INDEX ASSERTIONS_QUALIFIER_ENID_IDX
	ON ASSERTIONS(QUALIFIER_ENID);
CREATE INDEX ASSERTIONS_VALUE_ENID_IDX
	ON ASSERTIONS(VALUE_ENID);
CREATE INDEX ASSERTIONS_INID_IDX
	ON ASSERTIONS(INID);
CREATE INDEX EXPRESSIONS_EUUID_IDX
	ON EXPRESSIONS(EUUID);
CREATE INDEX EXPRESSIONS_CNID_IDX
	ON EXPRESSIONS(CNID);
CREATE INDEX INTERVALS_ISTART_IDX
	ON INTERVALS(ISTART);
CREATE INDEX INTERVALS_IEND_IDX
	ON INTERVALS(IEND);
CREATE INDEX INTERVALS_IUUID_IDX
	ON INTERVALS(IUUID);
CREATE INDEX DOCUMENTS_DUUID_IDX
	ON DOCUMENTS(DUUID);
CREATE INDEX DOCUMENTS_PATIENTNID_IDX
	ON DOCUMENTS(PATIENTNID);
CREATE INDEX DOCUMENTS_INID_IDX
	ON DOCUMENTS(INID);
CREATE INDEX DOCUMENTS_PROVIDERNID_IDX
	ON DOCUMENTS(PROVIDERNID);
CREATE INDEX PERSONS_PUUID_IDX
	ON PERSONS(PUUID);

CREATE INDEX PNCS_LEGO_MAP_IDX
	ON PNCS_LEGO_MAP(PNCS_ID, PNCS_VALUE);
	
ALTER TABLE PNCS_LEGO_MAP
	ADD CONSTRAINT FK_PNCS_LEGO_MAP_DISCERNABLE_ENID
	FOREIGN KEY(DISCERNABLE_ENID)
	REFERENCES EXPRESSIONS(ENID);

ALTER TABLE PNCS_LEGO_MAP
	ADD CONSTRAINT FK_PNCS_LEGO_MAP_QUALIFIER_ENID
	FOREIGN KEY(QUALIFIER_ENID)
	REFERENCES EXPRESSIONS(ENID);
	
ALTER TABLE PNCS_LEGO_MAP
	ADD CONSTRAINT FK_PNCS_LEGO_MAP_VALUE_ENID
	FOREIGN KEY(VALUE_ENID)
	REFERENCES EXPRESSIONS(ENID);

ALTER TABLE ASSERTIONS
	ADD CONSTRAINT FK_ASSERTIONS_DNID
	FOREIGN KEY(DNID)
	REFERENCES DOCUMENTS(DNID);
ALTER TABLE ASSERTIONS
	ADD CONSTRAINT FK_ASSERTIONS_INID
	FOREIGN KEY(INID)
	REFERENCES INTERVALS(INID);
ALTER TABLE ASSERTIONS
	ADD CONSTRAINT FK_ASSERTIONS_VALUE_ENID
	FOREIGN KEY(VALUE_ENID)
	REFERENCES EXPRESSIONS(ENID);
ALTER TABLE ASSERTIONS
	ADD CONSTRAINT FK_ASSERTIONS_QUALIFIER_ENID
	FOREIGN KEY(QUALIFIER_ENID)
	REFERENCES EXPRESSIONS(ENID);
ALTER TABLE ASSERTIONS
	ADD CONSTRAINT FK_ASSERTIONS_DISCERNABLE_ENID
	FOREIGN KEY(DISCERNABLE_ENID)
	REFERENCES EXPRESSIONS(ENID);
ALTER TABLE ASSERTIONS
	ADD CONSTRAINT FK_ASSERTIONS_SECTION_ENID
	FOREIGN KEY(SECTION_ENID)
	REFERENCES EXPRESSIONS(ENID);
ALTER TABLE DOCUMENTS
	ADD CONSTRAINT FK_DOCUMENTS_INID
	FOREIGN KEY(INID)
	REFERENCES INTERVALS(INID);
ALTER TABLE DOCUMENTS
	ADD CONSTRAINT FK_DOCUMENTS_PROVIDERNID
	FOREIGN KEY(PROVIDERNID)
	REFERENCES PERSONS(PNID);
ALTER TABLE DOCUMENTS
	ADD CONSTRAINT FK_DOCUMENTS_PATIENTNID
	FOREIGN KEY(PATIENTNID)
	REFERENCES PERSONS(PNID);
