/*
Database: edd-store
Objects: TABLE, INDEX
*/

DROP TABLE PERSONS;
DROP TABLE INTERVALS;
DROP TABLE EXPRESSIONS;
DROP TABLE DOCUMENTS;
DROP TABLE ASSERTIONS;

CREATE TABLE ASSERTIONS  ( 
	AUUID           	CHAR(36) NOT NULL,
	DNID            	INTEGER NOT NULL,
	SEQ_IN_DOC      	SMALLINT NOT NULL,
	SECTION_ENID    	INTEGER NOT NULL,
	DISCERNABLE_ENID	INTEGER NOT NULL,
	QUALIFIER_ENID  	INTEGER NOT NULL,
	VALUE_ENID      	INTEGER NOT NULL,
	INID            	INTEGER NOT NULL,
	CONSTRAINT ASSERTIONS_PK PRIMARY KEY(AUUID)
);

CREATE TABLE DOCUMENTS  ( 
	DUUID      	CHAR(36) NOT NULL,
	DNID       	INTEGER GENERATED ALWAYS AS IDENTITY,
	PATIENTNID 	INTEGER NOT NULL,
	PROVIDERNID	INTEGER,
	INID       	INTEGER NOT NULL,
	CONSTRAINT DOCUMENTS_PK PRIMARY KEY(DNID)
);

CREATE TABLE EXPRESSIONS  ( 
	EXPRESSION	VARCHAR(2048) NOT NULL,
	EUUID     	CHAR(36) NOT NULL,
	ENID      	INTEGER GENERATED ALWAYS AS IDENTITY,
	CNID      	INTEGER NOT NULL,
	CONSTRAINT EXPRESSIONS_PK PRIMARY KEY(ENID)
);
CREATE TABLE INTERVALS  ( 
	ISTART	DATE NOT NULL,
	IEND  	DATE NOT NULL,
	IUUID 	CHAR(36) NOT NULL,
	INID  	INTEGER GENERATED ALWAYS AS IDENTITY,
	CONSTRAINT INTERVALS_PK PRIMARY KEY(INID)
);

CREATE TABLE PERSONS  ( 
	PUUID    	CHAR(36) NOT NULL,
	PNID     	INTEGER GENERATED ALWAYS AS IDENTITY,
	LASTNAME 	VARCHAR(128) NOT NULL,
	FIRSTNAME	VARCHAR(128) NOT NULL,
	DOB      	DATE NOT NULL,
	CONSTRAINT PERSONS_PK PRIMARY KEY(PNID)
)
;
CREATE INDEX ASSERTIONS_DNID_IDX
	ON ASSERTIONS(DNID);
CREATE INDEX ASSERTIONS_SECTION_ENID_IDX
	ON ASSERTIONS(SECTION_ENID);
CREATE INDEX ASSERTIONS_DISCERNABLE_ENID_IDX
	ON ASSERTIONS(DISCERNABLE_ENID);
CREATE INDEX ASSERTIONS_QUALIFIER_ENID_IDX
	ON ASSERTIONS(QUALIFIER_ENID);
CREATE INDEX ASSERTIONS_VALUE_ENID_IDX
	ON ASSERTIONS(VALUE_ENID);
CREATE INDEX ASSERTIONS_INID_IDX
	ON ASSERTIONS(INID);
CREATE INDEX EXPRESSIONS_EUUID_IDX
	ON EXPRESSIONS(EUUID);
CREATE INDEX EXPRESSIONS_CNID_IDX
	ON EXPRESSIONS(CNID);
CREATE INDEX INTERVALS_ISTART_IDX
	ON INTERVALS(ISTART);
CREATE INDEX INTERVALS_IEND_IDX
	ON INTERVALS(IEND);
CREATE INDEX INTERVALS_IUUID_IDX
	ON INTERVALS(IUUID);
CREATE INDEX DOCUMENTS_DUUID_IDX
	ON DOCUMENTS(DUUID);
CREATE INDEX DOCUMENTS_PATIENTNID_IDX
	ON DOCUMENTS(PATIENTNID);
CREATE INDEX DOCUMENTS_INID_IDX
	ON DOCUMENTS(INID);
CREATE INDEX DOCUMENTS_PROVIDERNID_IDX
	ON DOCUMENTS(PROVIDERNID);
CREATE INDEX PERSONS_PUUID_IDX
	ON PERSONS(PUUID);

ALTER TABLE ASSERTIONS
	ADD CONSTRAINT FK_DNID_TO_DOC_DNID
	FOREIGN KEY(DNID)
	REFERENCES DOCUMENTS(DNID);

ALTER TABLE ASSERTIONS
	ADD CONSTRAINT FK_INID_TO_INT_INID
	FOREIGN KEY(INID)
	REFERENCES INTERVALS(INID);

ALTER TABLE ASSERTIONS
	ADD CONSTRAINT FK_VALUE_ENID_EXP_ENID
	FOREIGN KEY(VALUE_ENID)
	REFERENCES EXPRESSIONS(ENID);

ALTER TABLE ASSERTIONS
	ADD CONSTRAINT FK_QUALIFIER_ENID_EXP_ENID
	FOREIGN KEY(QUALIFIER_ENID)
	REFERENCES EXPRESSIONS(ENID);

ALTER TABLE ASSERTIONS
	ADD CONSTRAINT FK_DISCERNABLE_ENID_EXP_ENID
	FOREIGN KEY(DISCERNABLE_ENID)
	REFERENCES EXPRESSIONS(ENID);

ALTER TABLE ASSERTIONS
	ADD CONSTRAINT FK_SECTION_ENID_EXP_ENID
	FOREIGN KEY(SECTION_ENID)
	REFERENCES EXPRESSIONS(ENID);

ALTER TABLE DOCUMENTS
	ADD CONSTRAINT FK_INID_INT_INID
	FOREIGN KEY(INID)
	REFERENCES INTERVALS(INID);

ALTER TABLE DOCUMENTS
	ADD CONSTRAINT FK_DOCUMENTS_PROVIDERNID_PERSON_PNID
	FOREIGN KEY(PROVIDERNID)
	REFERENCES PERSONS(PNID);

ALTER TABLE DOCUMENTS
	ADD CONSTRAINT FK_DOCUMENTS_PATIENTNID_PERSON_PNID
	FOREIGN KEY(PATIENTNID)
	REFERENCES PERSONS(PNID);
